
services:
  ros1:
    build:
      context: ./ros_noetic/
      dockerfile: Dockerfile
    tty: true

  ros2:  
    # image: osrf/ros:humble-desktop
    build:
      context: ./ros2_humble/
      dockerfile: Dockerfile
    environment:
      - "DISPLAY=${DISPLAY}"
      - "QT_X11_NO_MITSHM=1"
      # - "ROS_MASTER_URI=http://192.168.0.46:11311"
      # - "ROS_IP=192.168.0.18"
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "/etc/localtime:/etc/localtime:ro"
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    command: rviz2
    tty: true

  bridge:
    image: ros:foxy-ros1-bridge # Need to use foxy
    environment:
      - "ROS_HOSTNAME=bridge"
      - "ROS_MASTER_URI=http://ros1:11311"
      # - "ROS_MASTER_URI=http://192.168.0.46:11311"
      # - "ROS_IP=192.168.0.18"
    command: ros2 run ros1_bridge dynamic_bridge
